name: JUnit Tests

on: [push]

jobs:
  build:
    name : Run JUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: mvn test
      - name: Check test results
        if: steps.test.outputs.num_tests_passed < 5
        run: echo "less than 5 tests passed"
      - name: Allow commit if tests passed
        if: steps.test.outputs.num_tests_passed >= 5
        run: git commit -a -m "Tests passed"
